# Generated by Django 5.0.6 on 2024-11-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stk_push', '0003_transaction_payer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payer_name',
        ),
        migrations.AddField(
            model_name='transaction',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
